### ISSUE TITLE
Remove FontAwesome dependency

### ISSUE THREAD

**Issue by ghost** [entozoon/custom-checkbox-radio-scss#1]

**Comment by entozoon** [comment]
👋 Hey dude. Are you suggesting not to make use of font-awesome at all?
A nice feature request - I can imagine little poly clip mask elements, or even SVG data. 

Pull requests welcome! 😉 

As for using font awesome 5 instead, I know they changed the font name for no reason (sigh)

**Comment by entozoon** [comment]
Perhaps @mredwardmilner could offer some advice?
The principle does seem sound, e.g 
https://codepen.io/entozoon/pen/rreVoP?editors=1100
(but SVG would be better - allowing smooth edges)

**Comment by entozoon** [comment]
Here is a CSS encoded SVG example, which seems like a great option. I'll whip up a fork and try it
https://codepen.io/entozoon/pen/gjoMZx?editors=1100

**Comment by entozoon** [comment]
https://github.com/entozoon/custom-checkbox-radio-scss/pull/2
